pipeline:
  build:
    image: paeti/ipnntensorflow
    commands:
      - git clone https://github.com/Paeti/IPNeuronaleNetze /notebooks/IPNeuronaleNetze
      - make -C /notebooks/IPNeuronaleNetze ci_test
