version: '3'

networks:
  backend:
    driver: bridge

services:
  age-model-service:
    image: tensorflow/serving:latest
    volumes:
      - ./models_production/models/Age:/models/Age
    environment:
      - MODEL_NAME=Age
    networks:
      - backend

  gender-model-service:
    image: tensorflow/serving:latest
    volumes:
      - ./models_production/models/Gender:/models/Gender
    environment:
      - MODEL_NAME=Gender
    networks:
      - backend

  web-service:
    build: ./web
    volumes:
      - ./web:/web
      - ./data:/data
    ports:
      - 5000:5000
    depends_on:
      - age-model-service
      - gender-model-service
    networks:
      - backend
